# Generated by Django 3.2.19 on 2024-04-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='L10n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_distance', models.CharField(blank=True, choices=[('chain', 'chain'), ('chain_benoit', 'chain_benoit'), ('chain_sears', 'chain_sears'), ('british_chain_benoit', 'british_chain_benoit'), ('british_chain_sears', 'british_chain_sears'), ('british_chain_sears_truncated', 'british_chain_sears_truncated'), ('cm', 'cm'), ('british_ft', 'british_ft'), ('british_yd', 'british_yd'), ('clarke_ft', 'clarke_ft'), ('clarke_link', 'clarke_link'), ('fathom', 'fathom'), ('ft', 'ft'), ('furlong', 'furlong'), ('german_m', 'german_m'), ('gold_coast_ft', 'gold_coast_ft'), ('indian_yd', 'indian_yd'), ('inch', 'inch'), ('km', 'km'), ('link', 'link'), ('link_benoit', 'link_benoit'), ('link_sears', 'link_sears'), ('m', 'm'), ('mi', 'mi'), ('mm', 'mm'), ('nm', 'nm'), ('nm_uk', 'nm_uk'), ('rod', 'rod'), ('sears_yd', 'sears_yd'), ('survey_ft', 'survey_ft'), ('um', 'um'), ('yd', 'yd'), ('hm', 'hm'), ('dm', 'dm')], max_length=64, null=True)),
                ('unit_area', models.CharField(blank=True, choices=[('sq_chain', 'sq_chain'), ('sq_chain_benoit', 'sq_chain_benoit'), ('sq_chain_sears', 'sq_chain_sears'), ('sq_british_chain_benoit', 'sq_british_chain_benoit'), ('sq_british_chain_sears', 'sq_british_chain_sears'), ('sq_british_chain_sears_truncated', 'sq_british_chain_sears_truncated'), ('sq_cm', 'sq_cm'), ('sq_british_ft', 'sq_british_ft'), ('sq_british_yd', 'sq_british_yd'), ('sq_clarke_ft', 'sq_clarke_ft'), ('sq_clarke_link', 'sq_clarke_link'), ('sq_fathom', 'sq_fathom'), ('sq_ft', 'sq_ft'), ('sq_furlong', 'sq_furlong'), ('sq_german_m', 'sq_german_m'), ('sq_gold_coast_ft', 'sq_gold_coast_ft'), ('sq_indian_yd', 'sq_indian_yd'), ('sq_inch', 'sq_inch'), ('sq_km', 'sq_km'), ('sq_link', 'sq_link'), ('sq_link_benoit', 'sq_link_benoit'), ('sq_link_sears', 'sq_link_sears'), ('sq_m', 'sq_m'), ('sq_mi', 'sq_mi'), ('sq_mm', 'sq_mm'), ('sq_nm', 'sq_nm'), ('sq_nm_uk', 'sq_nm_uk'), ('sq_rod', 'sq_rod'), ('sq_sears_yd', 'sq_sears_yd'), ('sq_survey_ft', 'sq_survey_ft'), ('sq_um', 'sq_um'), ('sq_yd', 'sq_yd'), ('ha', 'ha'), ('acre', 'acre'), ('feddan', 'feddan'), ('mu', 'mŭ')], max_length=64, null=True)),
                ('unit_weight', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('mg', 'mg'), ('ton', 'ton'), ('lb', 'lb'), ('short ton', 'short ton'), ('市斤', '市斤')], max_length=64, null=True)),
                ('unit_volume', models.CharField(blank=True, choices=[('cu_chain', 'cu_chain'), ('cu_chain_benoit', 'cu_chain_benoit'), ('cu_chain_sears', 'cu_chain_sears'), ('cu_british_chain_benoit', 'cu_british_chain_benoit'), ('cu_british_chain_sears', 'cu_british_chain_sears'), ('cu_british_chain_sears_truncated', 'cu_british_chain_sears_truncated'), ('cu_cm', 'cu_cm'), ('cu_british_ft', 'cu_british_ft'), ('cu_british_yd', 'cu_british_yd'), ('cu_clarke_ft', 'cu_clarke_ft'), ('cu_clarke_link', 'cu_clarke_link'), ('cu_fathom', 'cu_fathom'), ('cu_ft', 'cu_ft'), ('cu_furlong', 'cu_furlong'), ('cu_german_m', 'cu_german_m'), ('cu_gold_coast_ft', 'cu_gold_coast_ft'), ('cu_indian_yd', 'cu_indian_yd'), ('cu_inch', 'cu_inch'), ('cu_km', 'cu_km'), ('cu_link', 'cu_link'), ('cu_link_benoit', 'cu_link_benoit'), ('cu_link_sears', 'cu_link_sears'), ('cu_m', 'cu_m'), ('cu_mi', 'cu_mi'), ('cu_mm', 'cu_mm'), ('cu_nm', 'cu_nm'), ('cu_nm_uk', 'cu_nm_uk'), ('cu_rod', 'cu_rod'), ('cu_sears_yd', 'cu_sears_yd'), ('cu_survey_ft', 'cu_survey_ft'), ('cu_um', 'cu_um'), ('cu_yd', 'cu_yd'), ('cu_hm', 'cu_hm'), ('cu_dm', 'cu_dm'), ('l', 'l'), ('gal', 'gal'), ('cl', 'cl'), ('ml', 'ml')], max_length=64, null=True)),
                ('unit_temp', models.CharField(blank=True, choices=[('C', '°C'), ('F', '°F'), ('K', 'K')], max_length=64, null=True)),
                ('unit_velocity', models.CharField(blank=True, choices=[('mps', 'm/s'), ('kmh', 'km/h'), ('mph', 'mph')], max_length=64, null=True)),
                ('unit_precipitation', models.CharField(blank=True, choices=[('mm', 'mm'), ('inch', 'inch')], max_length=64, null=True)),
            ],
        ),
    ]
